server:
  port: 9101

## MULTIPART (MultipartProperties)
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
      max-request-size: 2MB
## File Storage Properties
file:
  upload-dir: ./uploads
